//! Per-contract private state, end to end.
//!
//! A contract's **private state** is off-chain data its stateful witnesses read
//! and write between calls. It never touches the chain, but it must survive
//! across calls. This example deploys a contract whose circuit calls a witness,
//! and shows the SDK's load → witness → persist loop doing real work.
//!
//! The `secret-counter` contract (see `devnet/contracts/secret-counter`):
//!
//! ```compact
//! export ledger total: Counter;
//! witness next_secret(): Uint<16>;          // value comes from private state
//! export circuit contribute(): Uint<16> {
//!   const s = next_secret();
//!   total.increment(disclose(s));           // fold the secret into public total
//!   return disclose(s);
//! }
//! ```
//!
//! The witness is a **typed method over a typed private state** (generated by
//! the `contract!` macro): no string dispatch, no `Value`, no byte (de)coding.
//! Our `PrivateState` is a running counter; each `next_secret()` returns the
//! next value and advances it. The SDK loads that state before each call and
//! persists it after — so the second `contribute()` discloses 2 only because it
//! saw the 1 the first call stored. The chain sees only the disclosed
//! contributions (`total` = 1, then 3); the counter stays off-chain.
//!
//! Runs against the shared local devnet (`devnet/docker-compose.yml`); see
//! README.md. The private-state store also supports password-encrypted
//! export/import for backup — see `docs/private-state.md`.

use std::sync::Arc;

use midnight_provider::{
    FsPrivateStateProvider, MidnightProvider, Network, PrivateStateProvider, Seed,
};

mod secret_counter {
    compact_bindgen::contract!("../../devnet/contracts/secret-counter/compiled/contract-info.json");
}

/// Node/indexer URLs default to the local devnet; override with the
/// `MIDNIGHT_NODE_URL` / `MIDNIGHT_INDEXER_URL` env vars to run elsewhere.
fn env_or(name: &str, default: &str) -> String {
    std::env::var(name).unwrap_or_else(|_| default.to_string())
}
const ZK_KEYS_DIR: &str = concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/../../devnet/contracts/secret-counter/compiled"
);

/// Dev node genesis wallet seed (funded with NIGHT tokens at genesis).
const DEV_WALLET_SEED: &str = "0000000000000000000000000000000000000000000000000000000000000001";

/// The off-chain half of the contract's `next_secret` witness — a typed method
/// over a typed private state.
///
/// `PrivateState = u64` is a running counter. Each call advances it and returns
/// the next value. The SDK loads the state into `ps` before the circuit runs
/// and persists it after; this impl never touches storage, `Value`, or bytes.
///
/// The method returns `Result<_, WitnessError>`: this witness is infallible so
/// it always returns `Ok`, but a witness backed by fallible I/O (a keystore, an
/// OS CSPRNG) can return `Err` to abort the call instead of panicking.
struct SecretWitness;

impl secret_counter::Witnesses for SecretWitness {
    type PrivateState = u64;

    fn next_secret(&self, ps: &mut u64) -> Result<u16, secret_counter::WitnessError> {
        *ps += 1;
        Ok(*ps as u16)
    }
}

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    println!("=== Midnight Private State Example ===\n");

    // A durable, contract-scoped private-state store. A real app would use
    // `FsPrivateStateProvider::with_default_dir()` (`~/.midnight/private-state/`);
    // a temp dir keeps the example repeatable.
    let dir = std::env::temp_dir().join("midnight-private-state-example");
    let _ = std::fs::remove_dir_all(&dir);
    let store: Arc<dyn PrivateStateProvider> = Arc::new(FsPrivateStateProvider::new(&dir));

    println!("0. Syncing wallet and attaching the private-state store...");
    let seed = Seed::from_hex(DEV_WALLET_SEED)?;
    let node_url = env_or("MIDNIGHT_NODE_URL", "ws://127.0.0.1:9944");
    let indexer_url = env_or("MIDNIGHT_INDEXER_URL", "http://127.0.0.1:8088");
    let provider = MidnightProvider::new(&node_url, &indexer_url)?
        .with_private_state(store)
        .sync_wallet(seed, Network::Undeployed)
        .await?;
    println!("   synced.\n");

    // 1. Deploy the secret-counter contract.
    println!("1. Deploying secret-counter...");
    let pending = secret_counter::Contract::deploy(&provider)
        .with_initial_state(secret_counter::LedgerInitialState::default())
        .with_zk_config(ZK_KEYS_DIR)
        .send()
        .await?;
    let (_, pending) = pending.wait_best().await?;
    let contract = pending.into_contract().await?;
    println!("   address: {}", contract.address());
    println!(
        "   on-chain total = {}\n",
        contract.ledger().await?.total()?
    );

    // 2 & 3. Call `contribute()` twice. The witness supplies the next secret
    //        from the private state; the SDK persists the advance after each
    //        call, so call #2 loads what call #1 wrote and discloses 2.
    for call in 1..=2 {
        println!("{}. Calling contribute()...", call + 1);
        let returned: u16 = contract
            .circuits()
            .with_witnesses(&SecretWitness)
            .contribute()
            .await?;
        println!(
            "   witness disclosed {returned}; on-chain total = {}",
            contract.ledger().await?.total()?
        );
    }

    println!(
        "\nThe second call disclosed 2 because the SDK loaded and persisted the\n\
         counter the first call wrote — the private state survives across calls\n\
         while the chain sees only the disclosed contributions (total = 1, then 3).\n\
         The state is on disk under {}, so it also survives restarts.",
        dir.display()
    );
    println!("\n=== Done ===");
    Ok(())
}
