[package]
name = "example-shielded-transfer"
version = "0.1.0"
edition.workspace = true
publish = false

[features]
ledger-8 = ["midnight-provider/ledger-8", "midnight-wallet/ledger-8", "midnight-provider/bindgen"]

[dependencies]
midnight-wallet = { workspace = true }
midnight-provider = { workspace = true }
hex = { workspace = true }
tokio = { workspace = true }
tracing-subscriber = { workspace = true }
