(analyzed-ir (compiler-version "0.33.122") (language-version "0.25.107")
  (runtime-version "0.18.107")
  (exports (contribute . %contribute.0) (total . %total.1))
  (contract-types)
  (kernel-declaration (%kernel.4 () (exported #f) (Kernel)))
  (public-ledger-declaration
    (public-ledger-array (%total.1 (0) (exported #t) (Counter)))
    (constructor () (tuple)))
  (witness %next_secret.2 () (tunsigned 65535))
  (circuit %contribute.0 (exported #t) (pure #f) (proof #t) ()
    (tunsigned 65535)
    (let* (((%s.3 (tunsigned 65535)) (call %next_secret.2)))
      (seq (public-ledger %total.1 update (0) increment (ttuple)
             (instructions
               (idx (cached #f) (pushPath #t) (path ((align 0 1))))
               (addi (immediate (value->int (var-ref %s.3))))
               (ins (cached #t) (n 1)))
             (var-ref %s.3))
           (return (var-ref %s.3))))))
