[package]
name = "midnight-core"
version = "0.1.0"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
description = "Meta-crate for the midnight-rs SDK — re-exports all sub-crates"

[features]
default = ["provider", "contract", "indexer", "crypto", "wallet"]
provider = ["dep:midnight-provider"]
contract = ["dep:midnight-contract", "dep:compact-bindgen"]
indexer = ["dep:midnight-indexer-client"]
crypto = ["dep:midnight-crypto"]
wallet = ["dep:midnight-wallet"]

ledger-8 = ["midnight-provider?/ledger-8", "midnight-provider?/bindgen", "midnight-contract?/ledger-8", "midnight-wallet?/ledger-8"]

[dependencies]
midnight-indexer-client = { workspace = true, optional = true }
midnight-provider = { workspace = true, optional = true }
midnight-wallet = { workspace = true, optional = true }
midnight-contract = { workspace = true, optional = true }
compact-bindgen = { workspace = true, optional = true }
midnight-crypto = { workspace = true, optional = true }
